.eslintrc
.github/pull_request_template.md
.github/workflows/assign-reviewers.yml
.github/workflows/validate.yml

Jira: [JFDZR9-]
Fix for Auto Assign hook
<details>
</details>
<hr />

Setup fixes

---

src/CategoryDropdown/CategoryDropdown.tsx

JFDZR9ASU-21 categorydropdown menu created

---

src/SignInButton/SignInButton.tsx
src/components/Header/Header.tsx
src/utils/firebase/firebase.config.ts

Jfdzr9 asu 38 firebase config

---

src/components/Header/Header.tsx

JFDZR9ASU-27-added link to CompanyLogo

---

package-lock.json
package.json
src/App.tsx
src/SignInButton/SignInButton.tsx

Jira: [JFDZR9ASU-92]
Routing was prepared

Routing was prepared

---

src/App.tsx
src/SignOutButton/SignOutButton.tsx
src/UserPanelButton/UserPanelButton.tsx
src/components/Header/Header.styled.ts
src/components/Header/HeaderUser.tsx

JFDZR9ASU-79 user panel header created

---

src/App.tsx
src/components/BottomNavigation/BottomNavigation.components.tsx
src/components/Buttons/Button.styled.ts
src/components/Buttons/SmallButton.component.tsx
src/components/Input/Input.styled.ts
src/pages/MainPage.tsx

Jira: [JFDZR9ASU-93]
Main Page was added

MainPage file was added and improved styles of buttons and input

---

src/App.tsx
src/components/Header/Header.tsx
src/main.tsx

Jfdzr9 asu 92 routing

---

src/components/HowDoesItWork/HowDoesItWork.component.tsx
src/components/HowDoesItWork/HowDoesItWork.styled.ts

JFDZR9ASU 58 How does it work component

---

src/App.tsx
src/components/BottomNavigation/BottomNavigation.component.tsx
src/components/HowDoesItWork/HowDoesItWork.component.tsx

JFDZR9ASU 58 Added Link in BottomNvigation and HowDoesItWork

---

src/App.tsx
src/UI/Title.styled.ts
src/components/BottomNavigation/BottomNavigation.component.tsx
src/components/Buttons/Button.styled.ts
src/components/HowDoesItWork/HowDoesItWork.styled.ts
src/pages/HowDoesItWorkBorrowPage.tsx
src/pages/HowDoesItWorkLendPage.tsx
src/pages/UserPanelPageBorrow.tsx
src/pages/UserPanelPageLend.tsx

Jira: [JFDZR9ASU-99]
User Panel skeleton page was created

Jfdzr9 asu 99 szkielet panelu uzytkownika

---

src/components/BottomNavigation/BottomNavigation.component.tsx
src/components/Opinion/Opinion.component.tsx
src/components/Opinion/Opinion.styled.ts
src/components/Opinion/OpinionUser.component.tsx
src/components/SingleCardOpinion/SingleCardOpinion.component.tsx
src/components/SingleCardOpinion/SingleCardOpinion.styled.ts

JFDZR9ASU 83 Created opinion single card and component

---

.prettierrc
package-lock.json
src/App.tsx
src/components/AddProductPage/AddNewProduct.component.tsx
src/components/AddProductPage/AddNewProduct.styled.ts
src/pages/AddProductPage.tsx
src/pages/SignInPage.tsx

Jfdzr9 asu 95 add product window

---

src/App.tsx
src/components/BottomNavigation/BottomNavigation.component.tsx
src/pages/OpinionsPage.tsx
src/pages/OpinionsPageUser.tsx

JFDZR9ASU 82 Created opinions pages

---

package-lock.json
package.json
src/App.tsx
src/CategoryDropdown/CategoryDropdown.tsx
src/components/AddProductPage/AddNewProduct.component.tsx
src/components/AddProductPage/AddNewProduct.styled.ts

Jira: [JFDZR9ASU-113]
AddNewProduct function was finished. I changed some things in CategoryDropdown compponent to make the function work. Please check it out and approve.

Jfdzr9 asu 113 add product function

---

src/components/HowDoesItWork/HowDoesItWork.component.tsx
src/components/Products/Product.component.tsx
src/components/Products/Product.styled.ts
src/components/SingleCard/SingleCard.component.tsx
src/components/SingleCard/SingleCard.styled.ts

added pic and text for borrow/land cards

---

package-lock.json
package.json
src/GoogleButton/SignInGoogle.tsx
src/components/Input/Input.componentpassword.tsx
src/pages/SignInPage.tsx
src/utils/firebase/firebase.config.ts

sign in with firebase and google

---

.prettierrc
src/App.tsx
src/components/AddNewOpinion/AddNewOpinion.component.tsx
src/components/AddNewOpinion/AddNewOpinion.styled.ts
src/components/BottomNavigation/BottomNavigation.component.tsx
src/components/Opinion/OpinionUser.component.tsx
src/pages/AddOpinionPage.tsx
src/pages/OpinionsPageUser.tsx

JFDZR9ASU 125 Created AddOpinionPage

---

src/components/AddProductPage/AddNewProduct.component.tsx
src/components/Products/Product.component.tsx
src/components/Products/Product.styled.ts
src/components/SingleCardProduct/SingleCardProduct.component.tsx

Jfdzr9 asu 119

---

src/components/AddNewOpinion/AddNewOpinion.component.tsx
src/components/Opinion/Opinion.styled.ts
src/components/SingleCardOpinion/SingleCardOpinion.component.tsx
src/components/SingleCardOpinion/SingleCardOpinion.styled.ts

JFDZR9ASU 83 126 Fixed Opinion

---

package-lock.json
package.json
src/App.tsx
src/Footer/Footer.styled.ts
src/components/Products/Product.component.tsx

sliding books on main page

---

src/components/SingleCardOpinion/SingleCardOpinion.styled.ts

Fixed stars

---

netlify.toml

Netlify config

---

src/components/SingleCardOpinion/SingleCardOpinion.styled.ts

Fixed stars again

---

src/components/Input/Input.componentpassword.tsx
src/pages/SignInPage.tsx

JFDZR9ASU-131 enter log in added

---

src/App.tsx
src/CompanyLogo/CompanyLogo.styles.ts
src/components/Header/Header.styled.ts
src/components/SignIn/SignIn.styled.ts
src/pages/ForgotPasswordPage.tsx
src/pages/SignInPage.tsx

JFDZR9ASU-132 forgot password option added

---

src/components/AddProductPage/AddNewProduct.component.tsx
src/components/Product/ProductsOwner.component.tsx
src/pages/UserPanelPageBorrow.tsx

JFDZR9ASU-122 usser borrow product added

---

src/components/AddProductPage/AddNewProduct.component.tsx

preview image has been added

---

src/components/Opinion/Opinion.styled.ts
src/components/SingleCardOpinion/SingleCardOpinion.component.tsx
src/components/SingleCardOpinion/SingleCardOpinion.styled.ts

JFDZR9ASU 150 Opinion changed - Added arrows

---

src/SignOutButton/SignOutButton.tsx
src/components/Product/Product.component.tsx
src/pages/SignInPage.tsx

JFDZR9ASU-153 removed user coll from mainpage

---

src/components/Opinion/Opinion.component.tsx
src/components/Opinion/OpinionUser.component.tsx
src/components/SingleCardOpinion/SingleCardOpinion.component.tsx
src/components/SingleCardOpinion/SingleCardOpinion.styled.ts

JFDZR9ASU 150 Opinion fixed

---

src/components/Product/Product.component.tsx
src/components/Product/ProductsOwner.component.tsx

JDFZR9ASU-135 new collection added

---

src/components/AddProductPage/AddNewProductSport.component.tsx
src/components/AddProductPage/AddNewProductTools.component.tsx

JFDZR9ASU 156 Created AddNewProductSport and AddNewProductTools

---

src/CategoryDropdown/CategoryDropdowncopy.tsx
src/components/Header/Header.tsx
src/components/Product/Product.component.tsx

JFDZR9ASU-138 sorting by category

---

src/CategoryDropdown/CategoryDropdownSecond.tsx
src/pages/AddProductPage.tsx

 JFDZR9ASU-157-Create-CategoryDropdownSecond-and-sort-forms

---

src/components/Product/Product.component.tsx

removed from mainpage currentsign in user

---

src/CategoryDropdown/CategoryDropdownMain.tsx
src/components/Header/Header.tsx
src/components/Product/Product.component.tsx

JFDZR9ASU0115 filterbyinput

---

src/App.tsx
src/components/Product/Product.component.tsx
src/pages/OneSingleProductPage.tsx

89-good working new page

---

src/CategoryDropdown/CategoryDropdownSecond.tsx
src/pages/OneSingleProductPage.tsx

Jfdzr9 asu 89 one single product page

---

package-lock.json
package.json
src/components/Product/Product.component.tsx
src/components/Product/ProductsOwner.component.tsx
src/components/Products/Product.styled.ts
src/components/SingleCardOpinion/SingleCardOpinion.component.tsx
theme/globalStyles.ts

Library of Carousel was changed. Please do _npm i_

Library of Carousel was chenged

---

src/App.tsx
src/Context/AuthContext.tsx
src/SignInButton/SignInButton.tsx
src/components/Product/ProductsOwner.component.tsx
src/components/UserData/UserDataButton.tsx
src/pages/UserDataPanel.tsx

JFDZR9ASU-185 data user

---

src/CategoryDropdown/CategoryDropdownSecond.styled.ts
src/CategoryDropdown/CategoryDropdownSecond.tsx
src/Footer/Footer.styled.ts
src/components/AddProductPage/AddNewProduct.styled.ts
src/components/Header/Header.styled.ts
src/components/OneSingleProduct/OneSingleProduct.styled.ts
src/components/Products/Product.styled.ts
src/components/TopNavigation/TopNavigatioon.styled.ts
src/pages/OneSingleProductPage.tsx

Jfdzr9 asu 174 responsive product page

---

package-lock.json
package.json
src/SignInButton/SignInButton.styled.ts
src/SignInButton/SignInButton.tsx
src/pages/UserDataPanel.tsx

JFDZR9ASU-185-useravatar

---

src/SignInButton/SignInButton.tsx
src/UserPanelButton/UserPanelButton.tsx
src/components/SignIn/SignInButton.tsx
src/components/UserData/UserDataButton.tsx

Comit jfdzr9 asu 185

---

src/SignInButton/SignInButton.tsx
src/UserPanelButton/UserPanelButton.tsx
src/components/SignIn/SignInButton.tsx
src/components/UserData/UserDataButton.tsx

Reverts infoshareacademy/jfdzr9-team-ArchITects-of-the-safe-Universe#81

Revert "Comit jfdzr9 asu 185"

---

package-lock.json
package.json
src/SignInButton/SignInButton.styled.ts
src/SignInButton/SignInButton.tsx
src/pages/UserDataPanel.tsx

Reverts infoshareacademy/jfdzr9-team-ArchITects-of-the-safe-Universe#79

Revert "JFDZR9ASU-185-useravatar"

---

src/AddOpinionButton/AddOpinionButton.tsx
src/App.tsx
src/OpinionButton/OpinionButton.tsx
src/RentingProductButton/RentingProductButton.component.tsx
src/StartRentingButton/StartRentingButton.tsx
src/components/AddNewOpinion/AddNewOpinion.component.tsx
src/components/Contact/Contact.component.tsx
src/components/Contact/Contact.styled.ts
src/pages/ContactPage.tsx
src/pages/OneSingleProductPage.tsx
src/utils/firebase/auth.ts

Jfdzr9 asu 162 170 contact

---

package-lock.json
package.json
src/SignInButton/SignInButton.styled.ts
src/SignInButton/SignInButton.tsx
src/pages/UserDataPanel.tsx

Reverts infoshareacademy/jfdzr9-team-ArchITects-of-the-safe-Universe#84

Revert "Revert "JFDZR9ASU-185-useravatar""

---

src/SignInButton/SignInButton.tsx
src/UserPanelButton/UserPanelButton.tsx
src/components/SignIn/SignInButton.tsx
src/components/UserData/UserDataButton.tsx

Reverts infoshareacademy/jfdzr9-team-ArchITects-of-the-safe-Universe#83

Revert "Revert "Comit jfdzr9 asu 185""

---

src/App.tsx
src/CategoryDropdown/CategoryDropdownSecond.styled.ts
src/CompanyLogo/CompanyLogo.styles.ts
src/Footer/Footer.styled.ts
src/SignInButton/SignInButton.styled.ts
src/SignInButton/SignInButton.tsx
src/components/AddProductPage/AddNewProduct.component.tsx
src/components/AddProductPage/AddNewProduct.styled.ts
src/components/AddProductPage/AddNewProductSport.component.tsx
src/components/AddProductPage/AddNewProductTools.component.tsx
src/components/Header/Header.styled.ts
src/components/Layout/Layout.component.tsx
src/components/Layout/Layout.styled.ts
src/components/OneSingleProduct/OneSingleProduct.styled.ts
src/components/Products/Product.styled.ts
src/pages/AddProductPage.tsx
theme/globalStyles.ts

responsive of the addProduct page was added

---

src/components/UserData/UserData.styled.ts
src/pages/UserDataPanel.tsx

the responsiveness of the user data page has been added

---

src/components/Opinion/Opinion.styled.ts
src/components/SingleCardOpinion/SingleCardOpinion.component.tsx
src/components/SingleCardOpinion/SingleCardOpinion.styled.ts

responsive opinions page has been added

---

src/components/AddNewOpinion/AddNewOpinion.component.tsx
src/components/AddNewOpinion/AddNewOpinion.styled.ts
src/components/Header/Header.styled.ts
src/components/Header/Header.tsx

Jfdzr9 asu 192 responsiveness of the add opnions page

---

src/pages/SignInPage.tsx

jfdzr9asu-187-userdata fixed some bug

---

src/components/Product/ProductsOwner.component.tsx
src/pages/UserDataPanel.tsx

JFDZR9ASU-some code fixed, status,input phone number

---

src/pages/UserDataPanel.tsx

only letter in name,lastname and location added

---

src/SignInButton/SignInButton.tsx
src/components/Header/Header.tsx
src/pages/SignInPage.tsx
src/pages/UserDataPanel.tsx

userdatafixed

---

src/ContactButton/ContactButton.component.tsx
src/components/Contact/Contact.component.tsx
src/pages/OneSingleProductPage.tsx

Added email address for contact

---

src/Footer/Footer.styled.ts
src/components/Buttons/Button.styled.ts
src/components/HowDoesItWork/HowDoesItWork.component.tsx
src/components/SingleCard/SingleCard.styled.ts
src/pages/HowDoesItWorkLendPage.tsx

how does it works pages styles were fixed

---

src/pages/SignInPage.tsx
src/pages/UserDataPanel.tsx

alert changed to red text

---

src/components/Contact/Contact.component.tsx
src/components/Contact/Contact.styled.ts

Jfdzr9 asu contact

---

src/components/HowDoesItWork/HowDoesItWork.styled.ts
src/pages/HowDoesItWorkBorrowPage.tsx
src/pages/HowDoesItWorkLendPage.tsx

Display how does it work page was fixed

---

src/components/HowDoesItWork/HowDoesItWork.styled.ts

How does it work was fixed
